version: "3.8"

services:
  book-api:
    restart: always
    image: "theartofdevel.bookapi:latest"
    container_name: book-api
    env_file: 
      - [cite_start].env 
    environment:
    - [cite_start]ConnectionStrings__DockerConnection=Server=${CURUNT_DB};Database=Booksite;User Id=sa;Password=Dima1234!;TrustServerCertificate=True [cite: 1]
    networks:
      - my-app-net
    depends_on:
      databaseSql:
        condition: service_healthy
    ports:
      - "1000:8080"

  databaseSql:
    image: mcr.microsoft.com/mssql/server
    container_name: databaseSql
    environment:
      - ACCEPT_EULA=Y
      - [cite_start]MSSQL_SA_PASSWORD=Dima1234! [cite: 1]
    healthcheck:
      [cite_start]test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Dima1234!", "-Q", "SELECT 1"] [cite: 1]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - [cite_start]"1433:1433" [cite: 1]
    networks:
      - my-app-net

networks:
  my-app-net:
    [cite_start]external: true [cite: 1]
